<!-- Image Map Generated by http://www.image-map.net/ -->
@section('map')
<img src="/img/map.png" usemap="#image-map">
<map name="image-map">
<area target="" alt="Hokkaido" title="Hokkaido" name="Hokkaido" coords="594,5,594,161,651,162,651,142,811,142,811,4" shape="poly">
    <area target="" alt="Aomori" title="Aomori" name="Aomori" coords="594,185,751,232" shape="rect">
    <area target="" alt="Iwate" title="Iwate" name="Iwate" coords="675,235,751,292" shape="rect">
    <area target="" alt="Akita" title="Akita" name="Akita" coords="595,235,671,292" shape="rect">
    <area target="" alt="Miyagi" title="Miyagi" name="Miyagi" coords="674,295,751,352" shape="rect">
    <area target="" alt="Yamagata" title="Yamagata" name="Yamagata" coords="594,295,595,332,625,332,625,352,671,352,671,295" shape="poly">
    <area target="" alt="Fukushima" title="Fukushima" name="Fukushima" coords="625,355,751,412" shape="rect">
    <area target="" alt="Niigata" title="Niigata" name="Niigata" coords="545,355,595,355,595,335,621,335,621,412,544,412" shape="poly">
    <area target="" alt="Toyama" title="Toyama" name="Toyama" coords="485,355,541,412" shape="rect">
    <area target="" alt="Ishikawa" title="Ishikawa" name="Ishikawa" coords="445,335,481,412" shape="rect">
    <area target="" alt="Fukui" title="Fukui" name="Fukui" coords="481,415,482,472,405,472,404,435,444,435,444,415" shape="poly">
    <area target="" alt="Ibaraki" title="Ibaraki" name="Ibaraki" coords="715,415,752,493" shape="rect">
    <area target="" alt="Chiba" title="Chiba" name="Chiba" coords="715,495,751,632" shape="rect">
    <area target="" alt="Tochigi" title="Tochigi" name="Tochigi" coords="655,415,711,472" shape="rect">
    <area target="" alt="Gunma" title="Gunma" name="Gunma" coords="595,415,651,472" shape="rect">
    <area target="" alt="Saitama" title="Saitama" name="Saitama" coords="595,475,712,522" shape="rect">
    <area target="" alt="Tokyo" title="Tokyo" name="Tokyo" coords="625,525,625,572,681,572,681,553,711,553,711,525" shape="poly">
    <area target="" alt="Kanagawa" title="Kanagawa" name="Kanagawa" coords="681,633,681,575,594,575,594,602,625,602,625,632" shape="poly">
    <area target="" alt="Nagano" title="Nagano" name="Nagano" coords="525,415,525,573,561,572,561,522,591,522,591,415" shape="poly">
    <area target="" alt="Gifu" title="Gifu" name="Gifu" coords="484,416,521,572" shape="rect">
    <area target="" alt="Yamanashi" title="Yamanashi" name="Yamanashi" coords="565,525,621,572" shape="rect">
    <area target="" alt="Aichi" title="Aichi" name="Aichi" coords="485,576,542,632" shape="rect">
    <area target="" alt="Shizuoka" title="Shizuoka" name="Shizuoka" coords="545,632,621,632,621,606,591,606,591,575,545,575" shape="poly">
    <area target="" alt="Shiga" title="Shiga" name="Shiga" coords="445,475,482,532" shape="rect">
    <area target="" alt="Mie" title="Mie" name="Mie" coords="444,535,482,673" shape="rect">
    <area target="" alt="Kyoto" title="Kyoto" name="Kyoto" coords="365,435,364,533,442,532,442,475,402,474,401,435" shape="poly">
    <area target="" alt="Nara" title="Nara" name="Nara" coords="404,535,442,633" shape="rect">
    <area target="" alt="Osaka" title="Osaka" name="Osaka" coords="365,535,402,602" shape="rect">
    <area target="" alt="Wakayama" title="Wakayama" name="Wakayama" coords="364,605,364,673,441,673,441,636,401,635,401,605" shape="poly">
    <area target="" alt="Hyogo" title="Hyogo" name="Hyogo" coords="325,435,362,552" shape="rect">
    <area target="" alt="Tottori" title="Tottori" name="Tottori" coords="285,435,321,491" shape="rect">
    <area target="" alt="Okayama" title="Okayama" name="Okayama" coords="285,495,321,551" shape="rect">
    <area target="" alt="Shimane" title="Shimane" name="Shimane" coords="245,434,281,491" shape="rect">
    <area target="" alt="Hiroshima" title="Hiroshima" name="Hiroshima" coords="245,494,281,551" shape="rect">
    <area target="" alt="Yamaguchi" title="Yamaguchi" name="Yamaguchi" coords="205,435,241,551" shape="rect">
    <area target="" alt="Kagawa" title="Kagawa" name="Kagawa" coords="274,574,341,621" shape="rect">
    <area target="" alt="Tokushima" title="Tokushima" name="Tokushima" coords="275,624,342,671" shape="rect">
    <area target="" alt="Ehime" title="Ehime" name="Ehime" coords="205,574,272,622" shape="rect">
    <area target="" alt="Kochi" title="Kochi" name="Kochi" coords="205,625,272,672" shape="rect">
    <area target="" alt="Fukuoka" title="Fukuoka" name="Fukuoka" coords="181,435,182,472,141,471,142,521,85,522,85,435" shape="poly">
    <area target="" alt="Oita" title="Oita" name="Oita" coords="144,475,182,542" shape="rect">
    <area target="" alt="Miyazaki" title="Miyazaki" name="Miyazaki" coords="145,545,181,611" shape="rect">
    <area target="" alt="Kumamoto" title="Kumamoto" name="Kumamoto" coords="85,524,142,611" shape="rect">
    <area target="" alt="Kagoshima" title="Kagoshima" name="Kagoshima" coords="85,615,182,672" shape="rect">
    <area target="" alt="Saga" title="Saga" name="Saga" coords="45,434,82,521" shape="rect">
    <area target="" alt="Nagasaki" title="Nagasaki" name="Nagasaki" coords="5,434,41,522" shape="rect">
    <area target="" alt="Okinawa" title="Okinawa" name="Okinawa" coords="85,694,122,751" shape="rect">
</map>
@endsection